Repository Team-GAJI/GAJI-Server, pull requests merged in 2024-07, with the labels that each got.

#14 [FEATURE] 에러핸들러
  src/main/java/gaji/service/domain/test/TestController.java
  src/main/java/gaji/service/global/base/BaseResponse.java
  src/main/java/gaji/service/global/exception/ExceptionAdvice.java
  src/main/java/gaji/service/global/exception/RestApiException.java
  src/main/java/gaji/service/global/exception/code/BaseCodeDto.java
  src/main/java/gaji/service/global/exception/code/BaseErrorCodeInterface.java
  src/main/java/gaji/service/global/exception/code/BaseSuccessCodeInterface.java
  src/main/java/gaji/service/global/exception/code/status/GlobalErrorStatus.java
  src/main/java/gaji/service/global/exception/code/status/SuccessStatus.java
Labels: :sparkles: feature

#15 ✨ [Feature] 스웨거 구현
  build.gradle
  ersminyoungDesktopgithubGAJI-Server git fetch --all
  git
  src/main/java/gaji/service/config/SwaggerConfig.java
  src/main/java/gaji/service/domain/test/TestController.java
Labels: :sparkles: feature

#18 ⚙️ [CONFIG] RDS, S3 구축
  build.gradle
  src/main/java/gaji/service/aws/s3/AmazonS3Manager.java
  src/main/java/gaji/service/config/AmazonConfig.java
  src/main/java/gaji/service/util/uuid/Uuid.java
  src/main/java/gaji/service/util/uuid/UuidRepository.java
Labels: ⚙ Setting

#19 ✨ [Feature] S3 관련 기능 추가
  src/main/java/gaji/service/aws/s3/AmazonS3Manager.java
  src/main/java/gaji/service/config/AmazonConfig.java
  src/main/java/gaji/service/global/exception/code/status/GlobalErrorStatus.java
Labels: :sparkles: feature

#26 :sparkles: [feature] #23 - 커뮤니티 게시글 업로드 API 구현
  build.gradle
  src/main/java/gaji/service/ServiceApplication.java
  src/main/java/gaji/service/config/AmazonConfig.java
  src/main/java/gaji/service/domain/User.java
  src/main/java/gaji/service/domain/common/converter/HashtagConverter.java
  src/main/java/gaji/service/domain/common/entity/BaseEntity.java
  src/main/java/gaji/service/domain/common/entity/Hashtag.java
  src/main/java/gaji/service/domain/common/entity/SelectHashtag.java
  src/main/java/gaji/service/domain/common/repository/HashtagRepository.java
  src/main/java/gaji/service/domain/common/repository/SelectHashtagRepository.java
  src/main/java/gaji/service/domain/common/service/HashtagQueryService.java
  src/main/java/gaji/service/domain/common/service/HashtagQueryServiceImpl.java
  src/main/java/gaji/service/domain/enums/PostStatusEnum.java
  src/main/java/gaji/service/domain/enums/PostTypeEnum.java
  src/main/java/gaji/service/domain/post/annotation/ExistPostType.java
  src/main/java/gaji/service/domain/post/code/PostErrorStatus.java
  src/main/java/gaji/service/domain/post/converter/PostConverter.java
  src/main/java/gaji/service/domain/post/entity/Comment.java
  src/main/java/gaji/service/domain/post/entity/Post.java
  src/main/java/gaji/service/domain/post/entity/PostBookmark.java
  src/main/java/gaji/service/domain/post/entity/PostFile.java
  src/main/java/gaji/service/domain/post/entity/PostLikes.java
  src/main/java/gaji/service/domain/post/repository/PostRepository.java
  src/main/java/gaji/service/domain/post/service/PostCommandService.java
  src/main/java/gaji/service/domain/post/service/PostCommandServiceImpl.java
  src/main/java/gaji/service/domain/post/validation/PostTypeExistValidator.java
  src/main/java/gaji/service/domain/post/web/controller/PostRestController.java
  src/main/java/gaji/service/domain/post/web/dto/PostRequestDTO.java
  src/main/java/gaji/service/domain/post/web/dto/PostResponseDTO.java
  src/main/java/gaji/service/domain/recruite/Category.java
  src/main/java/gaji/service/domain/recruite/RecruitPost.java
  src/main/java/gaji/service/domain/user/repository/UserRepository.java
Labels: :sparkles: feature, ⚙ Setting

#33 ✨[Feature]#31 스터디 과제 할당 API
  src/main/java/gaji/service/domain/User.java
  src/main/java/gaji/service/domain/alram/RoomAlarm.java
  src/main/java/gaji/service/domain/myRepeat/MyRepeat.java
  src/main/java/gaji/service/domain/myRepeat/RepeatException.java
  src/main/java/gaji/service/domain/recruite/RecruitPost.java
  src/main/java/gaji/service/domain/room/code/RoomErrorStatus.java
  src/main/java/gaji/service/domain/room/converter/RoomConverter.java
  src/main/java/gaji/service/domain/room/entity/Event.java
  src/main/java/gaji/service/domain/room/entity/Material.java
  src/main/java/gaji/service/domain/room/entity/Room.java
  src/main/java/gaji/service/domain/room/entity/RoomNotice.java
  src/main/java/gaji/service/domain/room/entity/VoiceChat.java
  src/main/java/gaji/service/domain/room/entity/VoiceChatUser.java
  src/main/java/gaji/service/domain/room/entity/Way.java
  src/main/java/gaji/service/domain/room/repository/AssignmentRepository.java
  src/main/java/gaji/service/domain/room/repository/RoomRepository.java
  src/main/java/gaji/service/domain/room/service/RoomCommandService.java
  src/main/java/gaji/service/domain/room/service/RoomCommandServiceImpl.java
  src/main/java/gaji/service/domain/room/web/controller/RoomController.java
  src/main/java/gaji/service/domain/room/web/dto/RoomRequestDto.java
  src/main/java/gaji/service/domain/room/web/dto/RoomResponseDto.java
  src/main/java/gaji/service/domain/roomPost/RoomBoard.java
  src/main/java/gaji/service/domain/studyMate/Assignment.java
  src/main/java/gaji/service/domain/studyMate/Chat.java
  src/main/java/gaji/service/domain/studyMate/StudyApplicant.java
  src/main/java/gaji/service/domain/studyMate/StudyMate.java
  src/main/java/gaji/service/domain/studyMate/repository/StudyMateRepository.java
Labels: :sparkles: feature

#35 ✨ [FEATURE] 파일 API
  src/main/java/gaji/service/ServiceApplication.java
  src/main/java/gaji/service/aws/s3/AmazonS3Manager.java
  src/main/java/gaji/service/domain/file/controller/FileController.java
  src/main/java/gaji/service/domain/file/domain/Files.java
  src/main/java/gaji/service/domain/file/dto/response/FileCreateResponse.java
  src/main/java/gaji/service/domain/file/dto/response/FileDeleteResponse.java
  src/main/java/gaji/service/domain/file/mapper/FileMapper.java
  src/main/java/gaji/service/domain/file/repository/FileRepository.java
  src/main/java/gaji/service/domain/file/service/FileService.java
  src/main/java/gaji/service/domain/file/service/FileServiceImpl.java
  src/main/java/gaji/service/global/base/swagger/MultipartJackson2HttpMessageConverter.java
  src/main/java/gaji/service/global/enums/FileCategory.java
  src/main/java/gaji/service/global/exception/code/status/FilesErrorStatus.java
  src/main/java/gaji/service/global/exception/code/status/GlobalErrorStatus.java
  src/main/java/gaji/service/global/util/uuid/Uuid.java
  src/main/java/gaji/service/global/util/uuid/UuidRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: :sparkles: feature

#45 ✨ [feature] #29 - 커뮤니티 게시글 댓글, 북마크, 좋아요 API 구현
  build.gradle
  src/main/java/gaji/service/domain/common/annotation/CheckHashtagListElement.java
  src/main/java/gaji/service/domain/common/entity/BaseEntity.java
  src/main/java/gaji/service/domain/common/entity/Hashtag.java
  src/main/java/gaji/service/domain/common/entity/SelectHashtag.java
  src/main/java/gaji/service/domain/common/repository/SelectHashtagRepository.java
  src/main/java/gaji/service/domain/common/validation/HashtagListElementValidator.java
  src/main/java/gaji/service/domain/enums/CommentStatus.java
  src/main/java/gaji/service/domain/post/code/PostErrorStatus.java
  src/main/java/gaji/service/domain/post/converter/PostConverter.java
  src/main/java/gaji/service/domain/post/entity/Comment.java
  src/main/java/gaji/service/domain/post/entity/Post.java
  src/main/java/gaji/service/domain/post/entity/PostBookmark.java
  src/main/java/gaji/service/domain/post/entity/PostLikes.java
  src/main/java/gaji/service/domain/post/repository/CommentRepository.java
  src/main/java/gaji/service/domain/post/repository/PostBookmarkRepository.java
  src/main/java/gaji/service/domain/post/repository/PostLikesRepository.java
  src/main/java/gaji/service/domain/post/service/PostCommandService.java
  src/main/java/gaji/service/domain/post/service/PostCommandServiceImpl.java
  src/main/java/gaji/service/domain/post/web/controller/PostRestController.java
  src/main/java/gaji/service/domain/post/web/dto/PostRequestDTO.java
  src/main/java/gaji/service/domain/user/annotation/ExistUser.java
  src/main/java/gaji/service/domain/user/service/UserQueryService.java
  src/main/java/gaji/service/domain/user/service/UserQueryServiceImpl.java
  src/main/java/gaji/service/domain/user/validation/UserExistValidator.java
Labels: :sparkles: feature, :hammer: Fix
