Repository Team-GAJI/GAJI-Server, pull requests merged in 2024-08, with the labels that each got.

#56 ✨ [feature] #27 - oAuth2 소셜로그인 API 구현
  build.gradle
  src/main/java/gaji/service/config/SecurityConfig.java
  src/main/java/gaji/service/domain/User.java
  src/main/java/gaji/service/domain/enums/Gender.java
  src/main/java/gaji/service/domain/enums/ServiceRole.java
  src/main/java/gaji/service/domain/user/repository/UserRepository.java
  src/main/java/gaji/service/jwt/config/CorsMvcConfig.java
  src/main/java/gaji/service/jwt/controller/ReissueController.java
  src/main/java/gaji/service/jwt/dto/TokenUserDTO.java
  src/main/java/gaji/service/jwt/entity/RefreshEntity.java
  src/main/java/gaji/service/jwt/filter/CustomLogoutFilter.java
  src/main/java/gaji/service/jwt/filter/JWTFilter.java
  src/main/java/gaji/service/jwt/filter/JWTUtil.java
  src/main/java/gaji/service/jwt/rpository/RefreshRepository.java
  src/main/java/gaji/service/jwt/service/CustomSuccessHandler.java
  src/main/java/gaji/service/jwt/service/ReissueService.java
  src/main/java/gaji/service/jwt/service/TokenProviderService.java
  src/main/java/gaji/service/oauth2/controller/Test2Controller.java
  src/main/java/gaji/service/oauth2/dto/CustomOAuth2User.java
  src/main/java/gaji/service/oauth2/dto/OAuthUserDTO.java
  src/main/java/gaji/service/oauth2/dto/TransferUserDTO.java
  src/main/java/gaji/service/oauth2/response/GoogleResponse.java
  src/main/java/gaji/service/oauth2/response/NaverResponse.java
  src/main/java/gaji/service/oauth2/response/OAuth2Response.java
  src/main/java/gaji/service/oauth2/service/CustomOAuth2UserService.java
Labels: :sparkles: feature, :recycle: Refactor, ✅ Test

#34 ✨ [feature] #25 - 회원 쪽지 보내기 API 구현
  src/main/java/gaji/service/domain/Report.java
  src/main/java/gaji/service/domain/alram/Alarm.java
  src/main/java/gaji/service/domain/alram/UserAlarm.java
  src/main/java/gaji/service/domain/message/converter/MessageBodyConverter.java
  src/main/java/gaji/service/domain/message/converter/MessageConverter.java
  src/main/java/gaji/service/domain/message/entity/Message.java
  src/main/java/gaji/service/domain/message/entity/MessageBody.java
  src/main/java/gaji/service/domain/message/enums/MessageTypeEnum.java
  src/main/java/gaji/service/domain/message/repository/MessageBodyRepository.java
  src/main/java/gaji/service/domain/message/repository/MessageRepository.java
  src/main/java/gaji/service/domain/message/service/MessageCommandService.java
  src/main/java/gaji/service/domain/message/service/MessageCommandServiceImpl.java
  src/main/java/gaji/service/domain/message/service/MessageQueryService.java
  src/main/java/gaji/service/domain/message/service/MessageQueryServiceImpl.java
  src/main/java/gaji/service/domain/message/web/controller/MessageRestController.java
  src/main/java/gaji/service/domain/message/web/dto/MessageRequestDTO.java
  src/main/java/gaji/service/domain/message/web/dto/MessageResponseDTO.java
  src/main/java/gaji/service/domain/post/converter/PostConverter.java
  src/main/java/gaji/service/domain/post/entity/Comment.java
  src/main/java/gaji/service/domain/post/entity/Post.java
  src/main/java/gaji/service/domain/post/entity/PostBookmark.java
  src/main/java/gaji/service/domain/post/entity/PostFile.java
  src/main/java/gaji/service/domain/post/entity/PostLikes.java
  src/main/java/gaji/service/domain/post/repository/PostBookmarkRepository.java
  src/main/java/gaji/service/domain/post/repository/PostLikesRepository.java
  src/main/java/gaji/service/domain/post/service/PostCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruite/RecruitPost.java
  src/main/java/gaji/service/domain/recruite/RecruitPostBookmark.java
  src/main/java/gaji/service/domain/recruite/RecruitPostLikes.java
  src/main/java/gaji/service/domain/recruite/SearchKeyword.java
  src/main/java/gaji/service/domain/room/entity/Event.java
  src/main/java/gaji/service/domain/room/entity/VoiceChatUser.java
  src/main/java/gaji/service/domain/room/service/RoomCommandServiceImpl.java
  src/main/java/gaji/service/domain/roomPost/converter/RoomPostConverter.java
  src/main/java/gaji/service/domain/roomPost/entity/RoomComment.java
  src/main/java/gaji/service/domain/roomPost/entity/RoomCommentLikes.java
  src/main/java/gaji/service/domain/roomPost/entity/RoomPost.java
  src/main/java/gaji/service/domain/roomPost/entity/RoomPostBookmark.java
  src/main/java/gaji/service/domain/roomPost/entity/RoomPostFile.java
  src/main/java/gaji/service/domain/roomPost/entity/RoomPostLikes.java
  src/main/java/gaji/service/domain/roomPost/entity/RoomPostReport.java
  src/main/java/gaji/service/domain/roomPost/service/RoomPostCommandServiceImpl.java
  src/main/java/gaji/service/domain/studyMate/ChatMessage.java
  src/main/java/gaji/service/domain/studyMate/ChatUser.java
  src/main/java/gaji/service/domain/studyMate/StudyApplicant.java
  src/main/java/gaji/service/domain/studyMate/StudyMate.java
  src/main/java/gaji/service/domain/studyMate/UserAssignment.java
  src/main/java/gaji/service/domain/term/TermAgree.java
  src/main/java/gaji/service/domain/token.java
  src/main/java/gaji/service/domain/user/converter/UserConverter.java
  src/main/java/gaji/service/domain/user/entity/User.java
  src/main/java/gaji/service/domain/user/repository/UserRepository.java
  src/main/java/gaji/service/domain/user/service/UserCommandServiceImpl.java
  src/main/java/gaji/service/domain/user/service/UserQueryService.java
  src/main/java/gaji/service/domain/user/service/UserQueryServiceImpl.java
  src/main/java/gaji/service/domain/user/web/controller/UserRestController.java
  src/main/java/gaji/service/domain/user/web/dto/UserResponseDTO.java
  src/main/java/gaji/service/oauth2/service/CustomOAuth2UserService.java
Labels: :sparkles: feature

#55 ✨ [feature] #38 -스터디름 일정 등록 API 구현
  build.gradle
  src/main/java/gaji/service/domain/myRepeat/MyRepeat.java
  src/main/java/gaji/service/domain/myRepeat/RepeatException.java
  src/main/java/gaji/service/domain/room/code/RoomErrorStatus.java
  src/main/java/gaji/service/domain/room/converter/RoomConverter.java
  src/main/java/gaji/service/domain/room/entity/Room.java
  src/main/java/gaji/service/domain/room/entity/RoomEvent.java
  src/main/java/gaji/service/domain/room/repository/RoomEventRepository.java
  src/main/java/gaji/service/domain/room/repository/RoomRepository.java
  src/main/java/gaji/service/domain/room/repository/UserAssignmentRepository.java
  src/main/java/gaji/service/domain/room/service/RoomCommandService.java
  src/main/java/gaji/service/domain/room/service/RoomCommandServiceImpl.java
  src/main/java/gaji/service/domain/room/service/RoomQueryService.java
  src/main/java/gaji/service/domain/room/service/RoomQueryServiceImpl.java
  src/main/java/gaji/service/domain/room/web/controller/RoomController.java
  src/main/java/gaji/service/domain/room/web/dto/RoomRequestDto.java
  src/main/java/gaji/service/domain/roomPost/entity/RoomBoard.java
  src/main/java/gaji/service/domain/roomPost/entity/RoomPost.java
  src/main/java/gaji/service/domain/studyMate/Assignment.java
  src/main/java/gaji/service/domain/studyMate/UserAssignment.java
  src/main/java/gaji/service/domain/studyMate/code/StudyMateErrorStatus.java
  src/main/java/gaji/service/domain/studyMate/repository/StudyMateRepository.java
  src/main/java/gaji/service/domain/user/entity/User.java
  src/main/java/gaji/service/domain/user/service/UserQueryServiceImpl.java
  src/main/java/gaji/service/jwt/service/CustomSuccessHandler.java
Labels: :sparkles: feature, :recycle: Refactor

#63 ✨ [feature] #59 - 유저 Soft Delete 및 닉네임 변경 API 구현
  src/main/java/gaji/service/ServiceApplication.java
  src/main/java/gaji/service/config/SecurityConfig.java
  src/main/java/gaji/service/config/SwaggerConfig.java
  src/main/java/gaji/service/domain/enums/UserActive.java
  src/main/java/gaji/service/domain/user/code/UserErrorStatus.java
  src/main/java/gaji/service/domain/user/converter/UserConverter.java
  src/main/java/gaji/service/domain/user/entity/User.java
  src/main/java/gaji/service/domain/user/enums/UserDeletePeriod.java
  src/main/java/gaji/service/domain/user/repository/UserRepository.java
  src/main/java/gaji/service/domain/user/scheduler/UserScheduler.java
  src/main/java/gaji/service/domain/user/service/UserCommandService.java
  src/main/java/gaji/service/domain/user/service/UserCommandServiceImpl.java
  src/main/java/gaji/service/domain/user/web/controller/UserRestController.java
  src/main/java/gaji/service/domain/user/web/dto/UserRequestDTO.java
  src/main/java/gaji/service/domain/user/web/dto/UserResponseDTO.java
Labels: :sparkles: feature

#68 ✨ [feature] #65 - 공지사항 목록 조회 API 구현
  src/main/java/gaji/service/domain/recruit/converter/RecruitConverter.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruit/service/RecruitQueryServiceImpl.java
  src/main/java/gaji/service/domain/room/code/RoomErrorStatus.java
  src/main/java/gaji/service/domain/room/converter/RoomConverter.java
  src/main/java/gaji/service/domain/room/entity/NoticeConfirmation.java
  src/main/java/gaji/service/domain/room/entity/Room.java
  src/main/java/gaji/service/domain/room/entity/RoomEvent.java
  src/main/java/gaji/service/domain/room/entity/RoomNotice.java
  src/main/java/gaji/service/domain/room/repository/AssignmentRepository.java
  src/main/java/gaji/service/domain/room/repository/NoticeConfirmationRepository.java
  src/main/java/gaji/service/domain/room/repository/RoomEventRepository.java
  src/main/java/gaji/service/domain/room/repository/RoomNoticeRepository.java
  src/main/java/gaji/service/domain/room/repository/RoomQueryRepository.java
  src/main/java/gaji/service/domain/room/repository/RoomRepository.java
  src/main/java/gaji/service/domain/room/repository/UserAssignmentRepository.java
  src/main/java/gaji/service/domain/room/repository/WeeklyUserProgressRepository.java
  src/main/java/gaji/service/domain/room/service/RoomCommandService.java
  src/main/java/gaji/service/domain/room/service/RoomCommandServiceImpl.java
  src/main/java/gaji/service/domain/room/service/RoomQueryService.java
  src/main/java/gaji/service/domain/room/service/RoomQueryServiceImpl.java
  src/main/java/gaji/service/domain/room/web/controller/RoomController.java
  src/main/java/gaji/service/domain/room/web/dto/RoomRequestDto.java
  src/main/java/gaji/service/domain/room/web/dto/RoomResponseDto.java
  src/main/java/gaji/service/domain/roomPost/service/RoomPostCommandServiceImpl.java
  src/main/java/gaji/service/domain/studyMate/entity/Assignment.java
  src/main/java/gaji/service/domain/studyMate/entity/Chat.java
  src/main/java/gaji/service/domain/studyMate/entity/ChatMessage.java
  src/main/java/gaji/service/domain/studyMate/entity/ChatUser.java
  src/main/java/gaji/service/domain/studyMate/entity/StudyApplicant.java
  src/main/java/gaji/service/domain/studyMate/entity/StudyMate.java
  src/main/java/gaji/service/domain/studyMate/entity/UserAssignment.java
  src/main/java/gaji/service/domain/studyMate/entity/WeeklyUserProgress.java
  src/main/java/gaji/service/domain/studyMate/repository/StudyMateRepository.java
  src/main/java/gaji/service/domain/studyMate/service/StudyMateQueryService.java
  src/main/java/gaji/service/domain/studyMate/service/StudyMateQueryServiceImpl.java
  src/main/java/gaji/service/domain/studyMate/web/dto/ResponseDto.java
  src/main/java/gaji/service/domain/user/entity/User.java
Labels: :sparkles: feature, :recycle: Refactor

#96 🔨 CustomSuccessHandler 수정
  src/main/java/gaji/service/jwt/service/CustomSuccessHandler.java
Labels: ⚙ Setting, :hammer: Fix

#100 ♻️ yml 환경에 따라서 redeirct를 다르게 yml에서 url을 가져오는 변수 생성
  src/main/java/gaji/service/jwt/service/CustomSuccessHandler.java
Labels: ⚙ Setting

#91 🎇 [feature] #71 - 유저 게시글 조회 API
  src/main/java/gaji/service/config/SecurityConfig.java
  src/main/java/gaji/service/domain/post/repository/PostQueryDslRepository.java
  src/main/java/gaji/service/domain/post/repository/PostQueryDslRepositoryImpl.java
  src/main/java/gaji/service/domain/user/converter/UserConverter.java
  src/main/java/gaji/service/domain/user/service/UserQueryService.java
  src/main/java/gaji/service/domain/user/service/UserQueryServiceImpl.java
  src/main/java/gaji/service/domain/user/web/controller/UserRestController.java
  src/main/java/gaji/service/domain/user/web/dto/UserResponseDTO.java
Labels: :sparkles: feature

#105 ⚙[Setting] #104 - SecurityConfig, CorsMvcConfig 수정
  src/main/java/gaji/service/config/CorsMvcConfig.java
  src/main/java/gaji/service/config/SecurityConfig.java
Labels: ⚙ Setting

#106 ✨[feature] #90 - 스터디룸 트러블 슈팅 게시글 기능 구현 API
  src/main/java/gaji/service/domain/roomBoard/code/RoomPostErrorStatus.java
  src/main/java/gaji/service/domain/roomBoard/converter/RoomPostConverter.java
  src/main/java/gaji/service/domain/roomBoard/entity/RoomTroublePost.java
  src/main/java/gaji/service/domain/roomBoard/entity/RoomTroublePostBookmark.java
  src/main/java/gaji/service/domain/roomBoard/entity/RoomTroublePostLike.java
  src/main/java/gaji/service/domain/roomBoard/entity/TroublePostComment.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomPostCommentRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomTroublePostBookmarkRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomTroublePostLikeRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomTroublePostRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/TroublePostCommentRepository.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomPostQueryService.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomPostQueryServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomTroublePostCommandService.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomTroublePostCommandServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/web/controller/RoomTroublePostController.java
  src/main/java/gaji/service/domain/roomBoard/web/dto/RoomBoardRequestDto.java
  src/main/java/gaji/service/domain/roomBoard/web/dto/RoomBoardResponseDto.java
  src/main/java/gaji/service/domain/roomBoard/web/dto/RoomPostRequestDto.java
  src/main/java/gaji/service/domain/roomBoard/web/dto/RoomPostResponseDto.java
  src/main/java/gaji/service/domain/studyMate/entity/StudyMate.java
  src/main/java/gaji/service/domain/studyMate/service/StudyMateQueryService.java
  src/main/java/gaji/service/domain/studyMate/service/StudyMateQueryServiceImpl.java
  src/main/java/gaji/service/domain/user/entity/User.java
  src/main/java/gaji/service/oauth2/dto/TransferUserDTO.java
  src/main/java/gaji/service/oauth2/service/CustomOAuth2UserService.java
Labels: :sparkles: feature

#94 ✨ [feature] #85 - 스터디 모집 게시글 좋아요, 북마크 API
  src/main/java/gaji/service/domain/recruit/code/RecruitErrorStatus.java
  src/main/java/gaji/service/domain/recruit/converter/RecruitConverter.java
  src/main/java/gaji/service/domain/recruit/entity/RecruitPostBookmark.java
  src/main/java/gaji/service/domain/recruit/entity/RecruitPostLikes.java
  src/main/java/gaji/service/domain/recruit/repository/RecruitPostBookmarkRepository.java
  src/main/java/gaji/service/domain/recruit/repository/RecruitPostLikesRepository.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandService.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruit/web/controller/RecruitController.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitResponseDTO.java
  src/main/java/gaji/service/domain/room/entity/Room.java
Labels: :sparkles: feature

#111 🚚 [rename] #97 클래스 이름 변경
  src/main/java/gaji/service/domain/common/annotation/CheckHashtagBlank.java
  src/main/java/gaji/service/domain/common/annotation/CheckHashtagLength.java
  src/main/java/gaji/service/domain/common/converter/CategoryConverter.java
  src/main/java/gaji/service/domain/common/entity/Hashtag.java
  src/main/java/gaji/service/domain/common/service/CategoryService.java
  src/main/java/gaji/service/domain/common/service/CategoryServiceImpl.java
  src/main/java/gaji/service/domain/common/validation/HashtagBlankValidator.java
  src/main/java/gaji/service/domain/common/validation/HashtagLengthValidator.java
  src/main/java/gaji/service/domain/enums/PostStatusEnum.java
  src/main/java/gaji/service/domain/enums/PostTypeEnum.java
  src/main/java/gaji/service/domain/post/code/CommunityCommentErrorStatus.java
  src/main/java/gaji/service/domain/post/code/CommunityPostErrorStatus.java
  src/main/java/gaji/service/domain/post/converter/CommunityCommentConverter.java
  src/main/java/gaji/service/domain/post/converter/CommunityPostConverter.java
  src/main/java/gaji/service/domain/post/converter/PostStatusConverter.java
  src/main/java/gaji/service/domain/post/converter/PostTypeConverter.java
  src/main/java/gaji/service/domain/post/entity/CommnuityPost.java
  src/main/java/gaji/service/domain/post/entity/CommunityComment.java
  src/main/java/gaji/service/domain/post/entity/PostBookmark.java
  src/main/java/gaji/service/domain/post/entity/PostFile.java
  src/main/java/gaji/service/domain/post/entity/PostLikes.java
  src/main/java/gaji/service/domain/post/repository/CommentJpaRepository.java
  src/main/java/gaji/service/domain/post/repository/CommentQueryDslRepository.java
  src/main/java/gaji/service/domain/post/repository/CommentQueryDslRepositoryImpl.java
  src/main/java/gaji/service/domain/post/repository/CommunityCommentJpaRepository.java
  src/main/java/gaji/service/domain/post/repository/CommunityPostBookmarkRepository.java
  src/main/java/gaji/service/domain/post/repository/CommunityPostJpaRepository.java
  src/main/java/gaji/service/domain/post/repository/CommunityPostLikesRepository.java
  src/main/java/gaji/service/domain/post/repository/CommunityPostQueryDslRepository.java
  src/main/java/gaji/service/domain/post/repository/CommunityPostQueryDslRepositoryImpl.java
  src/main/java/gaji/service/domain/post/repository/PostBookmarkRepository.java
  src/main/java/gaji/service/domain/post/repository/PostJpaRepository.java
  src/main/java/gaji/service/domain/post/repository/PostLikesRepository.java
  src/main/java/gaji/service/domain/post/service/CommentService.java
  src/main/java/gaji/service/domain/post/service/CommentServiceImpl.java
  src/main/java/gaji/service/domain/post/service/CommunityCommentService.java
  src/main/java/gaji/service/domain/post/service/CommunityCommentServiceImpl.java
  src/main/java/gaji/service/domain/post/service/CommunityPostBookMarkService.java
  src/main/java/gaji/service/domain/post/service/CommunityPostBookMarkServiceImpl.java
  src/main/java/gaji/service/domain/post/service/CommunityPostCommandService.java
  src/main/java/gaji/service/domain/post/service/CommunityPostCommandServiceImpl.java
  src/main/java/gaji/service/domain/post/service/CommunityPostLikesService.java
  src/main/java/gaji/service/domain/post/service/CommunityPostLikesServiceImpl.java
  src/main/java/gaji/service/domain/post/service/CommunityPostQueryService.java
  src/main/java/gaji/service/domain/post/service/CommunityPostQueryServiceImpl.java
  src/main/java/gaji/service/domain/post/service/PostBookMarkService.java
  src/main/java/gaji/service/domain/post/service/PostBookMarkServiceImpl.java
  src/main/java/gaji/service/domain/post/service/PostCommandService.java
  src/main/java/gaji/service/domain/post/service/PostCommandServiceImpl.java
  src/main/java/gaji/service/domain/post/service/PostLikesService.java
  src/main/java/gaji/service/domain/post/service/PostQueryServiceImpl.java
  src/main/java/gaji/service/domain/post/validation/PostTypeExistValidator.java
  src/main/java/gaji/service/domain/post/web/controller/CommunityPostRestController.java
  src/main/java/gaji/service/domain/post/web/dto/CommunityPostResponseDTO.java
  src/main/java/gaji/service/domain/post/web/dto/PostRequestDTO.java
  src/main/java/gaji/service/domain/user/entity/User.java
  src/main/java/gaji/service/domain/user/validation/UserExistValidator.java
  src/main/java/gaji/service/global/exception/code/status/GlobalErrorStatus.java
  src/main/java/gaji/service/jwt/service/CustomSuccessHandler.java
Labels: :sparkles: feature, :hammer: Fix

#98 ✨ [feature] #86 - 스터디 댓글 작성, 삭제, 조회 API
  src/main/java/gaji/service/domain/common/repository/SelectCategoryRepository.java
  src/main/java/gaji/service/domain/common/service/CategoryService.java
  src/main/java/gaji/service/domain/common/service/CategoryServiceImpl.java
  src/main/java/gaji/service/domain/recruit/code/RecruitErrorStatus.java
  src/main/java/gaji/service/domain/recruit/converter/RecruitConverter.java
  src/main/java/gaji/service/domain/recruit/entity/StudyComment.java
  src/main/java/gaji/service/domain/recruit/repository/RecruitCustomRepository.java
  src/main/java/gaji/service/domain/recruit/repository/RecruitPostBookmarkRepository.java
  src/main/java/gaji/service/domain/recruit/repository/StudyCommentCustomRepository.java
  src/main/java/gaji/service/domain/recruit/repository/StudyCommentCustomRepositoryImpl.java
  src/main/java/gaji/service/domain/recruit/repository/StudyCommentRepository.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandService.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruit/service/RecruitQueryServiceImpl.java
  src/main/java/gaji/service/domain/recruit/service/StudyCommentCommandService.java
  src/main/java/gaji/service/domain/recruit/service/StudyCommentCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruit/service/StudyCommentQueryService.java
  src/main/java/gaji/service/domain/recruit/service/StudyCommentQueryServiceImpl.java
  src/main/java/gaji/service/domain/recruit/validation/CategoryExistValidator.java
  src/main/java/gaji/service/domain/recruit/web/controller/RecruitController.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitRequestDTO.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitResponseDTO.java
  src/main/java/gaji/service/domain/room/entity/Room.java
Labels: :sparkles: feature

#113 ✨ [feature] #60 - 스터디 모집 게시글 검색 기능 구현
  src/main/java/gaji/service/domain/recruit/code/RecruitErrorStatus.java
  src/main/java/gaji/service/domain/recruit/converter/RecruitConverter.java
  src/main/java/gaji/service/domain/recruit/repository/RecruitCustomRepository.java
  src/main/java/gaji/service/domain/recruit/repository/RecruitCustomRepositoryImpl.java
  src/main/java/gaji/service/domain/recruit/service/RecruitQueryService.java
  src/main/java/gaji/service/domain/recruit/service/RecruitQueryServiceImpl.java
  src/main/java/gaji/service/domain/recruit/web/controller/RecruitController.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitResponseDTO.java
Labels: :sparkles: feature, :hammer: Fix

#117 ✨ [feature] #116 - 스터디룸 게시글, 정보나눔 게시글, 트러블슈팅 게시글 상세 조회, 댓글 무한 스크롤 API 구현
  src/main/java/gaji/service/domain/roomBoard/entity/RoomInfo/InfoPostComment.java
  src/main/java/gaji/service/domain/roomBoard/entity/RoomPost/PostComment.java
  src/main/java/gaji/service/domain/roomBoard/entity/RoomTrouble/TroublePostComment.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomInfo/InfoPostCommentRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomInfo/RoomInfoPostRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomPost/PostCommentRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomTrouble/TroublePostCommentRepository.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomInfo/RoomInfoPostQueryService.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomInfo/RoomInfoPostQueryServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomPost/RoomPostQueryService.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomPost/RoomPostQueryServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomTrouble/RoomTroublePostQueryService.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomTrouble/RoomTroublePostQueryServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/web/controller/RoomInfoPostController.java
  src/main/java/gaji/service/domain/roomBoard/web/controller/RoomPostController.java
  src/main/java/gaji/service/domain/roomBoard/web/controller/RoomTroublePostController.java
  src/main/java/gaji/service/domain/roomBoard/web/dto/RoomPostResponseDto.java
Labels: :sparkles: feature

#120 ✨ [feature] 회원가입 완료 시에 닉네임 설정하는 창으로 redirect 하는 기능 구현
  src/main/java/gaji/service/ServiceApplication.java
  src/main/java/gaji/service/config/SecurityConfig.java
  src/main/java/gaji/service/config/WebConfig.java
  src/main/java/gaji/service/domain/room/entity/Room.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomInfo/RoomInfoPostRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomTrouble/TroublePostCommentRepository.java
  src/main/java/gaji/service/domain/roomBoard/web/controller/RoomTroublePostController.java
  src/main/java/gaji/service/domain/user/service/UserCommandService.java
  src/main/java/gaji/service/domain/user/service/UserCommandServiceImpl.java
  src/main/java/gaji/service/domain/user/service/UserQueryService.java
  src/main/java/gaji/service/domain/user/service/UserQueryServiceImpl.java
  src/main/java/gaji/service/global/util/uuid/Uuid.java
  src/main/java/gaji/service/jwt/filter/JWTFilter.java
  src/main/java/gaji/service/jwt/service/CustomSuccessHandler.java
  src/main/java/gaji/service/oauth2/controller/Test2Controller.java
  src/main/java/gaji/service/oauth2/dto/CustomOAuth2User.java
  src/main/java/gaji/service/oauth2/dto/OAuthUserDTO.java
  src/main/java/gaji/service/oauth2/dto/TransferUserDTO.java
  src/main/java/gaji/service/oauth2/service/CustomOAuth2UserService.java
Labels: :sparkles: feature

#122 ✨ [feature] 공지사항 확인 버튼 누른 유저 조회
  src/main/java/gaji/service/domain/room/entity/NoticeConfirmation.java
  src/main/java/gaji/service/domain/room/repository/NoticeConfirmationRepository.java
  src/main/java/gaji/service/domain/room/service/RoomCommandService.java
  src/main/java/gaji/service/domain/room/service/RoomCommandServiceImpl.java
  src/main/java/gaji/service/domain/room/service/RoomQueryService.java
  src/main/java/gaji/service/domain/room/service/RoomQueryServiceImpl.java
  src/main/java/gaji/service/domain/room/web/controller/RoomNoticeController.java
  src/main/java/gaji/service/domain/studyMate/repository/StudyMateRepository.java
Labels: :sparkles: feature, :recycle: Refactor

#126 ♻️ [refactor] #123 - 진행율 에러 수정
  src/main/java/gaji/service/domain/room/code/RoomErrorStatus.java
  src/main/java/gaji/service/domain/room/entity/NoticeConfirmation.java
  src/main/java/gaji/service/domain/room/repository/WeeklyUserProgressRepository.java
  src/main/java/gaji/service/domain/room/service/RoomCommandService.java
  src/main/java/gaji/service/domain/room/service/RoomCommandServiceImpl.java
  src/main/java/gaji/service/domain/room/service/RoomQueryServiceImpl.java
  src/main/java/gaji/service/domain/room/web/controller/RoomMainController.java
  src/main/java/gaji/service/domain/room/web/controller/RoomNoticeController.java
  src/main/java/gaji/service/domain/room/web/dto/RoomRequestDto.java
  src/main/java/gaji/service/domain/room/web/dto/RoomResponseDto.java
  src/main/java/gaji/service/domain/studyMate/entity/WeeklyUserProgress.java
  src/main/java/gaji/service/domain/studyMate/repository/StudyMateRepository.java
  src/main/java/gaji/service/jwt/service/CustomSuccessHandler.java
Labels: ⚙ Setting, :recycle: Refactor

#131 ⚙[setting] #130 - 쿼리로 access 토큰 전달
  src/main/java/gaji/service/jwt/service/CustomSuccessHandler.java
Labels: ⚙ Setting

#133 ♻️ [refactor] roomEvent 엔드포인트 수정
  src/main/java/gaji/service/domain/room/service/RoomQueryService.java
  src/main/java/gaji/service/domain/room/service/RoomQueryServiceImpl.java
  src/main/java/gaji/service/domain/room/web/controller/RoomMainController.java
Labels: :recycle: Refactor

#118 ✨ [feature] #112 - 스터디 가지기 API
  src/main/java/gaji/service/domain/recruit/converter/RecruitConverter.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandService.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruit/service/RecruitQueryService.java
  src/main/java/gaji/service/domain/recruit/service/RecruitQueryServiceImpl.java
  src/main/java/gaji/service/domain/recruit/web/controller/RecruitController.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitRequestDTO.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitResponseDTO.java
  src/main/java/gaji/service/domain/studyMate/code/StudyMateErrorStatus.java
  src/main/java/gaji/service/domain/studyMate/repository/StudyMateRepository.java
  src/main/java/gaji/service/domain/studyMate/service/StudyMateCommandService.java
  src/main/java/gaji/service/domain/studyMate/service/StudyMateCommandServiceImpl.java
  src/main/java/gaji/service/domain/studyMate/service/StudyMateQueryService.java
  src/main/java/gaji/service/domain/studyMate/service/StudyMateQueryServiceImpl.java
Labels: :sparkles: feature, :hammer: Fix

#137 ♻️ [refactor] 스터디룸 게시글(트러블슈팅 게시글, 게시글, 정보나눔 게시글) pathvriable 을 roomId 형태로 변경
  src/main/java/gaji/service/domain/room/repository/RoomEventRepository.java
  src/main/java/gaji/service/domain/room/repository/RoomNoticeRepository.java
  src/main/java/gaji/service/domain/room/service/RoomQueryService.java
  src/main/java/gaji/service/domain/room/service/RoomQueryServiceImpl.java
  src/main/java/gaji/service/domain/room/web/controller/RoomNoticeController.java
  src/main/java/gaji/service/domain/room/web/dto/RoomResponseDto.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomBoardRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomInfo/RoomInfoPostRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomPost/RoomPostRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomTrouble/RoomTroublePostRepository.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomTrouble/TroublePostCommentRepository.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomInfo/RoomInfoPostCommandServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomInfo/RoomInfoPostQueryServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomPost/RoomPostCommandServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomPost/RoomPostQueryService.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomPost/RoomPostQueryServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomTrouble/RoomTroublePostCommandServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomTrouble/RoomTroublePostQueryServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/web/controller/RoomInfoPostController.java
  src/main/java/gaji/service/domain/roomBoard/web/controller/RoomPostController.java
  src/main/java/gaji/service/domain/roomBoard/web/controller/RoomTroublePostController.java
Labels: :sparkles: feature, :recycle: Refactor

#129 :sparkles: [feature] #97 - 커뮤니티 게시글 검색 API
  src/main/java/gaji/service/domain/common/converter/CategoryConverter.java
  src/main/java/gaji/service/domain/common/repository/SelectCategoryQueryDslRepository.java
  src/main/java/gaji/service/domain/common/repository/SelectCategoryQueryDslRepositoryImpl.java
  src/main/java/gaji/service/domain/common/service/CategoryService.java
  src/main/java/gaji/service/domain/common/service/CategoryServiceImpl.java
  src/main/java/gaji/service/domain/common/validation/CategoryExistsValidator.java
  src/main/java/gaji/service/domain/enums/CategoryEnum.java
  src/main/java/gaji/service/domain/post/converter/CommunityCommentConverter.java
  src/main/java/gaji/service/domain/post/converter/CommunityPostConverter.java
  src/main/java/gaji/service/domain/post/converter/PostStatusConverter.java
  src/main/java/gaji/service/domain/post/converter/PostTypeConverter.java
  src/main/java/gaji/service/domain/post/converter/SortTypeConverter.java
  src/main/java/gaji/service/domain/post/repository/CommunityPostQueryDslRepository.java
  src/main/java/gaji/service/domain/post/repository/CommunityPostQueryDslRepositoryImpl.java
  src/main/java/gaji/service/domain/post/service/CommunityCommentService.java
  src/main/java/gaji/service/domain/post/service/CommunityCommentServiceImpl.java
  src/main/java/gaji/service/domain/post/service/CommunityPostCommandService.java
  src/main/java/gaji/service/domain/post/service/CommunityPostCommandServiceImpl.java
  src/main/java/gaji/service/domain/post/service/CommunityPostQueryService.java
  src/main/java/gaji/service/domain/post/service/CommunityPostQueryServiceImpl.java
  src/main/java/gaji/service/domain/post/web/controller/CommunityPostRestController.java
  src/main/java/gaji/service/domain/post/web/dto/CommunityPostCommentResponseDTO.java
  src/main/java/gaji/service/domain/post/web/dto/CommunityPostRequestDTO.java
  src/main/java/gaji/service/domain/post/web/dto/CommunityPostResponseDTO.java
  src/main/java/gaji/service/jwt/service/CustomSuccessHandler.java
  src/main/resources/application-dev.yml
Labels: :sparkles: feature, 🐞 BugFix, :hammer: Fix

#134 ✨ [feature] #87 - 스터디 삭제 및 수정API
  src/main/java/gaji/service/domain/common/entity/SelectCategory.java
  src/main/java/gaji/service/domain/common/repository/SelectCategoryRepository.java
  src/main/java/gaji/service/domain/common/service/CategoryService.java
  src/main/java/gaji/service/domain/common/service/CategoryServiceImpl.java
  src/main/java/gaji/service/domain/recruit/code/RecruitErrorStatus.java
  src/main/java/gaji/service/domain/recruit/converter/RecruitConverter.java
  src/main/java/gaji/service/domain/recruit/entity/StudyComment.java
  src/main/java/gaji/service/domain/recruit/repository/RecruitCustomRepositoryImpl.java
  src/main/java/gaji/service/domain/recruit/repository/StudyCommentRepository.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandService.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruit/service/RecruitQueryServiceImpl.java
  src/main/java/gaji/service/domain/recruit/service/StudyCommentCommandService.java
  src/main/java/gaji/service/domain/recruit/service/StudyCommentCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruit/validation/CategoryExistValidator.java
  src/main/java/gaji/service/domain/recruit/web/controller/RecruitController.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitRequestDTO.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitResponseDTO.java
  src/main/java/gaji/service/domain/room/entity/Room.java
  src/main/java/gaji/service/domain/room/repository/MaterialRepository.java
  src/main/java/gaji/service/domain/room/service/MaterialCommandService.java
  src/main/java/gaji/service/domain/room/service/MaterialCommandServiceImpl.java
  src/main/java/gaji/service/domain/room/service/RoomCommandService.java
  src/main/java/gaji/service/domain/room/service/RoomCommandServiceImpl.java
  src/main/java/gaji/service/domain/studyMate/code/StudyMateErrorStatus.java
Labels: :sparkles: feature, :hammer: Fix

#140 🔨 [fix] 스터디룸 메인 화면 게시글 조회, 스터디룸 일정 에러 수정
  src/main/java/gaji/service/domain/recruit/converter/RecruitConverter.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruit/service/RecruitQueryService.java
  src/main/java/gaji/service/domain/recruit/web/controller/RecruitController.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitRequestDTO.java
  src/main/java/gaji/service/domain/room/code/RoomErrorStatus.java
  src/main/java/gaji/service/domain/room/converter/RoomConverter.java
  src/main/java/gaji/service/domain/room/entity/RoomEvent.java
  src/main/java/gaji/service/domain/room/service/RoomCommandService.java
  src/main/java/gaji/service/domain/room/service/RoomCommandServiceImpl.java
  src/main/java/gaji/service/domain/room/web/controller/RoomMainController.java
  src/main/java/gaji/service/domain/room/web/dto/RoomRequestDto.java
  src/main/java/gaji/service/domain/room/web/dto/RoomResponseDto.java
  src/main/java/gaji/service/domain/roomBoard/repository/RoomPost/RoomPostRepository.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomPost/RoomPostQueryService.java
  src/main/java/gaji/service/domain/roomBoard/service/RoomPost/RoomPostQueryServiceImpl.java
  src/main/java/gaji/service/domain/roomBoard/web/dto/RoomPostResponseDto.java
  src/main/java/gaji/service/domain/studyMate/entity/Assignment.java
  src/main/java/gaji/service/domain/studyMate/entity/UserAssignment.java
Labels: :sparkles: feature, :recycle: Refactor, :hammer: Fix

#135 :art: [Fix] #67 - 스터디룸 가져오기 API 수정
  src/main/java/gaji/service/domain/post/repository/CommunityPostQueryDslRepositoryImpl.java
  src/main/java/gaji/service/domain/room/repository/RoomCustomRepository.java
  src/main/java/gaji/service/domain/room/repository/RoomCustomRepositoryImpl.java
  src/main/java/gaji/service/domain/roomBoard/entity/RoomBoard.java
  src/main/java/gaji/service/domain/user/service/UserQueryServiceImpl.java
Labels: :hammer: Fix

#143 🐞 [BugFix] 머지 중 에러 해결
  src/main/java/gaji/service/domain/common/service/CategoryService.java
  src/main/java/gaji/service/domain/common/service/CategoryServiceImpl.java
  src/main/java/gaji/service/domain/enums/CategoryEnum.java
  src/main/java/gaji/service/domain/post/converter/CommunityPostConverter.java
  src/main/java/gaji/service/domain/post/converter/PostStatusConverter.java
  src/main/java/gaji/service/domain/post/converter/PostTypeConverter.java
  src/main/java/gaji/service/domain/post/converter/SortTypeConverter.java
  src/main/java/gaji/service/domain/post/web/controller/CommunityPostRestController.java
  src/main/java/gaji/service/domain/post/web/dto/CommunityPostResponseDTO.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitRequestDTO.java
  src/main/java/gaji/service/domain/studyMate/entity/Assignment.java
Labels: 🐞 BugFix

#145 ✨ [feature] 공지사항 삭제 및 수정 API 구현
  src/main/java/gaji/service/domain/room/converter/RoomConverter.java
  src/main/java/gaji/service/domain/room/entity/RoomNotice.java
  src/main/java/gaji/service/domain/room/service/RoomCommandService.java
  src/main/java/gaji/service/domain/room/service/RoomCommandServiceImpl.java
  src/main/java/gaji/service/domain/room/service/RoomQueryService.java
  src/main/java/gaji/service/domain/room/service/RoomQueryServiceImpl.java
  src/main/java/gaji/service/domain/room/web/controller/RoomNoticeController.java
  src/main/java/gaji/service/domain/room/web/dto/RoomResponseDto.java
Labels: :sparkles: feature

#146 🔨 [fix] #87 - 스터디 수정 API 및 RequestDTO 검증 수정
  src/main/java/gaji/service/domain/common/validation/CategoryExistsValidator.java
  src/main/java/gaji/service/domain/recruit/annotation/ExistCategory.java
  src/main/java/gaji/service/domain/recruit/service/RecruitCommandServiceImpl.java
  src/main/java/gaji/service/domain/recruit/validation/CategoryExistValidator.java
  src/main/java/gaji/service/domain/recruit/web/dto/RecruitRequestDTO.java
Labels: :hammer: Fix
